[window]
opacity = 0.6

[font]
size = 15.0

[font.bold]
family = "Liberation Mono"
style = "Bold"

[font.bold_italic]
family = "Liberation Mono"
style = "Bold Italic"

[font.italic]
family = "Liberation Mono"
style = "Italic"

[font.normal]
family = "Liberation Mono"
style = "Regular"

[window.padding]
x = 12
y = 12
